name: CI
on: push
jobs:
  code_quality:
    name: Checks with black and isort
    runs-on: ubuntu-latest
    container: python:3.9
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run script
      run: |
       python -m pip install --upgrade pip
       pip install black isort pytest
       if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
       ls -la
       black --check .
       isort --check .
       py.test -x homework*
